/*
    Boost Software License - Version 1.0 - August 17th, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.

*/

#include "channelswidget.h"
#include "channellist.h"
#include <KDebug>
#include <qcheckbox.h>
#include "settings.h"
#include <QDir>
#include <KIO/DeleteJob>

ChannelsWidget::ChannelsWidget()
{
  //m_channels = Settings::channels();
  cl = new ChannelList::ChannelList();
  connect(cl, SIGNAL(fetched(XmlTvBase *)), this, SLOT(gotChannelsList()));
}

ChannelsWidget::~ChannelsWidget()
{

}

void ChannelsWidget::setupUi(QWidget* parent)
{
    Ui::channel_prefs::setupUi(parent);
    cl->fetch();
}

void ChannelsWidget::gotChannelsList()
{
    QList<QStringList> chanList;
    cl->getChannelsList(&chanList);
    
    QList<QStringList>::iterator chan;
    for (chan = chanList.begin(); chan != chanList.end(); ++chan) {
      QListWidgetItem *item = new QListWidgetItem((*chan).join(" - "), channelsList);
      item->setData(Qt::UserRole, (*chan).first());
      
      if ((!Settings::channels().isEmpty()) && Settings::channels().contains((*chan).first())) {
	item->setCheckState(Qt::Checked);
      } else {
	item->setCheckState(Qt::Unchecked);
      }
    }
    
    connect(channelsList, SIGNAL(itemChanged(QListWidgetItem *)), this, SLOT(slotChannelsChanged(QListWidgetItem *)));  
}

void ChannelsWidget::slotChannelsChanged(QListWidgetItem *item) {
    QStringList tempChannels = Settings::channels();
    QString channelId(item->data(Qt::UserRole).toString());
    
    if (item->checkState() == Qt::Checked) {
      tempChannels.append(channelId);
    } else {
      tempChannels.removeAll(channelId);
      
      // For this channel, get the list of existing data files
      QDir dataDir(QString(getenv("HOME")) + "/.kepg");
      QStringList dataFiles = dataDir.entryList(QStringList(channelId + "_*.xml.gz"), QDir::Files, QDir::Name);
      
      KUrl::List deleteList;
      QStringListIterator df(dataFiles);
      while (df.hasNext()) {
	QString dataFile(df.next());
	deleteList.append("file://" + QString(getenv("HOME")) + "/.kepg/" + dataFile);
      }

      // Now that we have our list of files to delete, fire off a DeleteJob
      KIO::DeleteJob *delJob = KIO::del(deleteList);
      delJob->start();
      
      // Remove the corresponding config settings
      KConfigGroup *tempConfigGroup = new KConfigGroup(KGlobal::config(), channelId);
      tempConfigGroup->deleteGroup();
      tempConfigGroup->sync();
      delete tempConfigGroup;
    }
    
    Settings::setChannels(tempChannels);
    
    //TODO: This needs to single the change to the KConfigDialogManager rather than actually writing to disk
    Settings::self()->writeConfig();
}

#include "channelswidget.moc"